#!/bin/sh
uci set network.lan.ipaddr="192.168.8.1"
uci commit network
/etc/init.d/network restart
sed -i "/^DISTRIB_DESCRIPTION='/s/'$/ Default'/" /etc/openwrt_release
[ -d "/etc/init.d" ] && chmod +x /etc/init.d/*
[ -e "/usr/bin/AdGuardHome/AdGuardHome" ] && chmod 755 /usr/bin/AdGuardHome/AdGuardHome
until [ "$( opkg list-installed 2>/dev/null| grep -c "^kernel")" -ne '0' ]; do
  sleep 1
done
if [ "$( opkg list-installed 2>/dev/null| grep -c "^luci-app-adguardhome")" -ne '0' ];then
uci batch << EOI
set AdGuardHome.AdGuardHome.enabled='1'
set AdGuardHome.AdGuardHome.httpport='3000'
set AdGuardHome.AdGuardHome.binpath='/usr/bin/AdGuardHome/AdGuardHome'
set AdGuardHome.AdGuardHome.waitonboot='1'
set AdGuardHome.AdGuardHome.redirect='dnsmasq-upstream'
set AdGuardHome.AdGuardHome.ucitracktest='1'
set AdGuardHome.AdGuardHome.old_redirect='dnsmasq-upstream'
set AdGuardHome.AdGuardHome.old_port='1745'
set AdGuardHome.AdGuardHome.old_enabled='1'
EOI
  uci commit AdGuardHome
  /etc/init.d/AdGuardHome restart
fi
if [ "$( opkg list-installed 2>/dev/null| grep -c "^dnsmasq")" -ne '0' ];then
  uci set dhcp.@dnsmasq[0].cachesize='0'
  uci commit dhcp
  /etc/init.d/dnsmasq restart
fi
uci commit
/etc/init.d/sing-box stop
/etc/init.d/sing-box disable
echo >> feeds.conf.default
echo 'src-git istore https://github.com/linkease/istore;main' >> feeds.conf.default
./scripts/feeds update istore
./scripts/feeds install -d y -p istore luci-app-store
exit 0

